### PR TITLE
Feature/tao 7161/new task queue used

### PR DESCRIPTION
**Pull request by gyszucs**
https://oat-sa.atlassian.net/browse/TAO-7161

To check it:
1. install wkhtmltopdf https://wkhtmltopdf.org/
2. install taoBooklets extension
3. in the configuration file `config/taoBooklet/wkhtmltopdf.conf.php` change the path `'binary'` to the real *wkhtmltopdf* execution file
4. Try to create and regenerate booklets from the backoffice

FYI: make sure that you have taoTaskQueue extension installed (and that script ` php index.php 'oat\taoTaskQueue\scripts\tools\RunWorker'` was run after the config was changed) 

**Depends on:** 
- [x] https://github.com/oat-sa/tao-core/pull/1867

### CODE REVIEW

**Comment by siwane** [comment]
As it is impacted by FileSerialiser that not working, I'm waiting for a fix not related to this PR

**Comment by zagovorichev** [comment]
@SergiiTao @siwane Update, booklets page was fixed, could you check this PR?

**Comment by gyszucs** [comment]
@zagovorichev Thanks for the back-end changes, they look good to me but not tested.

**Comment by zagovorichev** [comment]
@gyszucs only controllers were touched

**Comment by zagovorichev** [comment]
@gyszucs @SergiiTao @siwane Could anyone check this PR, pleeease?

**Comment by SergiiTao** [comment]
there is an error message on the result page.

**Comment by zagovorichev** [comment]
@SergiiTao I don't see error messages there

**Pull request merged**
