### PR TITLE
feat: Add taoBooklet to OPTION_GENERIS_SEARCH_WHITELIST

### PR DESCRIPTION
**Pull request by hectoras**
Associated Jira issue: [ADF-245](https://oat-sa.atlassian.net/browse/ADF-245)

### CODE REVIEW

**Review by gabrielfs7 — APPROVED** [review]
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

**Comment by gabrielfs7** [comment]
@hectoras would it be possible to extend the README.md with alternative instructions for installation since the current one did not work on the kitchend?

```
sudo apt-get update
sudo apt-get install wkhtmltopdf
sudo apt-get install libxrender1 fontconfig xvfb
sudo apt --fix-broken-install

wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
tar xf  wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
cd ./wkhtmltox/bin/
sudo cp -R ./* /usr/bin/
sudo cp -R ./* /usr/local/bin/
sudo apt --fix-broken-install
wkhtmltopdf -V
```

**Comment by AntonNeviarouski** [comment]
QA verified

**Comment by hectoras** [comment]
Released as [v4.1.0](https://github.com/oat-sa/extension-tao-booklet/releases/tag/v4.1.0).

**Pull request merged**
